package nl.errorsoft.esql.connection.ui;

import nl.errorsoft.esql.ui.util.Forms;
import nl.errorsoft.esql.database.Database;

import nl.errorsoft.esql.settings.Settings;
import nl.errorsoft.esql.connection.DatabaseDriver;
import nl.errorsoft.esql.connection.control.DatabaseDriverCC;
import nl.errorsoft.esql.designer.ui.diagram.Field;

/*
 * DriverUI.java
 *
 * Created on 6 april 2003, 0:51
 */

import java.awt.event.*;
import javax.swing.*;

/**
 *
 * @author  CoolKillaH
 */
public class DriverUI extends javax.swing.JDialog implements ActionListener, ItemListener {

	private DatabaseDriverCC dbcc;

	/** Creates new form DriverUI */
	public DriverUI(DatabaseDriverCC dbcc, java.awt.Frame parent) {
		super(parent, false);
		initComponents();
		this.dbcc = dbcc;
		this.setResizable(false);
		this.setLocationRelativeTo(parent);
		this.setVisible(true);
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	private void initComponents() {

		jTabbedPane1 = new javax.swing.JTabbedPane();
		jPanel1 = new javax.swing.JPanel();
		jPanel2 = new javax.swing.JPanel();
		jLabel1 = new javax.swing.JLabel();
		jtxtURL = new javax.swing.JTextField();
		jLabel2 = new javax.swing.JLabel();
		jtxtLibPath = new javax.swing.JTextField();
		jbtnBrowse = new javax.swing.JButton();
		jbtnBrowse.addActionListener(this);
		jLabel11 = new javax.swing.JLabel();
		jtxtClassName = new javax.swing.JTextField();
		jtxtDataOpenChar = new javax.swing.JTextField();
		jtxtDataCloseChar = new javax.swing.JTextField();
		jLabel3 = new javax.swing.JLabel();
		jLabel31 = new javax.swing.JLabel();
		jLabel311 = new javax.swing.JLabel();
		jLabel32 = new javax.swing.JLabel();
		jtxtFieldOpenChar = new javax.swing.JTextField();
		jtxtFieldCloseChar = new javax.swing.JTextField();
		jPanel3 = new javax.swing.JPanel();
		jcmbType = new javax.swing.JComboBox<>();
		jbtnClose = new javax.swing.JButton();
		jbtnClose.addActionListener(this);
		jbtnSave = new javax.swing.JButton();
		jbtnSave.addActionListener(this);

		setTitle("Driver properties");
		setResizable(false);
		addWindowListener(new java.awt.event.WindowAdapter() {
			public void windowClosing(java.awt.event.WindowEvent evt) {
				dispose();
			}
		});

		jLabel1.setText("Connection URL:");
		jLabel11.setText("Driver class-name:");
		jLabel3.setText("Data close char:");
		jLabel31.setText("Data open char:");
		jLabel311.setText("Field open char:");
		jLabel32.setText("Field close char:");
		jtxtURL.setColumns(20);
		for (javax.swing.JTextField c : new javax.swing.JTextField[]{jtxtFieldOpenChar, jtxtFieldCloseChar, jtxtDataOpenChar, jtxtDataCloseChar}) {
			c.setColumns(3);
		}
		jPanel2 = new Forms.Grid().row(jLabel11, jtxtClassName).row(jLabel1, jtxtURL).row(jLabel311, pair(jtxtFieldOpenChar, jLabel32, jtxtFieldCloseChar))
			.row(jLabel31, pair(jtxtDataOpenChar, jLabel3, jtxtDataCloseChar)).done();
		Forms.titled(jPanel2, "Driver properties");

		jcmbType.addItemListener(this);
		jPanel3.setLayout(new java.awt.BorderLayout());
		jPanel3.add(jcmbType);
		Forms.titled(jPanel3, "Database type");

		jPanel1 = Forms.padded(new Forms.Grid().full(jPanel3).full(jPanel2).done());
		jTabbedPane1.addTab("JDBC Settings", jPanel1);

		jbtnClose.setText("Cancel");
		jbtnSave.setText("Save");
		javax.swing.JPanel root = Forms.padded(new javax.swing.JPanel(new java.awt.BorderLayout()));
		root.add(jTabbedPane1, java.awt.BorderLayout.CENTER);
		root.add(Forms.buttonRow(jbtnSave, jbtnClose), java.awt.BorderLayout.SOUTH);
		setContentPane(root);
		pack();
	}

	/** An open and a close character on one row. */
	private static javax.swing.JPanel pair(java.awt.Component open, java.awt.Component closeLabel, java.awt.Component close) {
		javax.swing.JPanel p = new javax.swing.JPanel(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, Forms.GAP, 0));
		p.add(open);
		p.add(javax.swing.Box.createHorizontalStrut(Forms.PADDING));
		p.add(closeLabel);
		p.add(close);
		return p;
	}

	public void loadDrivers(DatabaseDriver[] dbda) {
		if (dbda != null && dbda.length > 0) {
			javax.swing.DefaultComboBoxModel<DatabaseDriver> dcm = new javax.swing.DefaultComboBoxModel<>();

			for (int i = 0; i < dbda.length; i++) {
				dcm.addElement(dbda[i]);
			}

			this.jcmbType.setModel(dcm);

			this.jtxtClassName.setText(dbda[0].getDriverClassName());
			this.jtxtDataOpenChar.setText(dbda[0].getDataOpenChar());
			this.jtxtDataCloseChar.setText(dbda[0].getDataCloseChar());
			this.jtxtFieldOpenChar.setText(dbda[0].getFieldOpenChar());
			this.jtxtFieldCloseChar.setText(dbda[0].getFieldCloseChar());
			this.jtxtLibPath.setText(dbda[0].getDriverFilePath());
			this.jtxtURL.setText(dbda[0].getDriverURL());
		}
	}

	public void actionPerformed(ActionEvent e) {
		if (e.getSource() == this.jbtnClose) {
			this.dispose();
		} else if (e.getSource() == this.jbtnSave) {
			dbcc.saveProperties(((DatabaseDriver) this.jcmbType.getSelectedItem()).getId(),
				((DatabaseDriver) this.jcmbType.getSelectedItem()).getDriverName(),
				this.jtxtURL.getText(),
				this.jtxtClassName.getText(),
				this.jtxtLibPath.getText(),
				this.jtxtFieldOpenChar.getText(),
				this.jtxtFieldCloseChar.getText(),
				this.jtxtDataOpenChar.getText(),
				this.jtxtDataCloseChar.getText());
		}
	}

	public void itemStateChanged(ItemEvent e) {
		Object src = e.getSource();

		if (src == jcmbType && jcmbType.getSelectedItem() != null && jcmbType.getSelectedItem() instanceof DatabaseDriver) {
			DatabaseDriver temp = (DatabaseDriver) jcmbType.getSelectedItem();
			this.jtxtClassName.setText(temp.getDriverClassName());
			this.jtxtDataOpenChar.setText(temp.getDataOpenChar());
			this.jtxtDataCloseChar.setText(temp.getDataCloseChar());
			this.jtxtFieldOpenChar.setText(temp.getFieldOpenChar());
			this.jtxtFieldCloseChar.setText(temp.getFieldCloseChar());
			this.jtxtLibPath.setText(temp.getDriverFilePath());
			this.jtxtURL.setText(temp.getDriverURL());
		}
	}

	// Variables declaration - do not modify
	private javax.swing.JButton jbtnClose;
	private javax.swing.JTextField jtxtClassName;
	private javax.swing.JComboBox<DatabaseDriver> jcmbType;
	private javax.swing.JTextField jtxtURL;
	private javax.swing.JTextField jtxtFieldCloseChar;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JButton jbtnSave;
	private javax.swing.JLabel jLabel32;
	private javax.swing.JLabel jLabel311;
	private javax.swing.JPanel jPanel3;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JButton jbtnBrowse;
	private javax.swing.JPanel jPanel2;
	private javax.swing.JTextField jtxtFieldOpenChar;
	private javax.swing.JLabel jLabel11;
	private javax.swing.JTextField jtxtDataCloseChar;
	private javax.swing.JTextField jtxtDataOpenChar;
	private javax.swing.JTextField jtxtLibPath;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JLabel jLabel31;
	private javax.swing.JTabbedPane jTabbedPane1;
	// End of variables declaration

}
