package nl.errorsoft.esql.job.ui;

import nl.errorsoft.esql.error.Dialogs;
/*
 * JDialog.java
 *
 * Created on 9 april 2003, 20:53
 */
import nl.errorsoft.esql.ui.util.EscapeToClose;
import javax.swing.*;

import nl.errorsoft.esql.ui.util.Forms;
import javax.swing.tree.*;
import javax.swing.event.*;
import java.awt.event.*;
import java.io.*;
/**
 *
 * @author  CoolKillaH
 */
public class ImportExportProgressUI extends javax.swing.JDialog {

	/** Creates new form JDialog */
	public ImportExportProgressUI(JDialog jm) {

		super(jm, "Import / Export progress");
		// Esc does not close this window: a running job must not be hidden by accident.
		getRootPane().putClientProperty(EscapeToClose.DISABLED, true);
		initComponents();
		this.setLocation(jm.getLocation().x + (int) ((jm.getSize().width - this.getSize().width) / 2),
			jm.getLocation().y + (int) ((jm.getSize().height - this.getSize().height) / 2));
		this.setVisible(true);
		this.toFront();
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	private void initComponents() {
		jProgressBar1 = new javax.swing.JProgressBar();
		jLabel1 = new javax.swing.JLabel();
		jButton1 = new javax.swing.JButton();

		addWindowListener(new java.awt.event.WindowAdapter() {
			public void windowClosing(java.awt.event.WindowEvent evt) {
				closeDialog(evt);
			}
		});
		jLabel1.setText("Import / Export progress");
		jButton1.setText("Close");
		jButton1.setEnabled(false);
		jProgressBar1.setPreferredSize(new java.awt.Dimension(330, jProgressBar1.getPreferredSize().height));

		JPanel root = Forms.padded(new JPanel(new java.awt.BorderLayout(0, Forms.GAP)));
		root.add(jLabel1, java.awt.BorderLayout.NORTH);
		root.add(jProgressBar1, java.awt.BorderLayout.CENTER);
		root.add(Forms.buttonRow(jButton1), java.awt.BorderLayout.SOUTH);
		setContentPane(root);
		pack();
	}

	public void setProgressValue(int percentage) {
		this.jProgressBar1.setValue(percentage);

		if (percentage == 100) {
			this.jButton1.setEnabled(true);
			Dialogs.info(this, getTitle(), "Completed.");
			this.dispose();
		}
	}

	/** Closes the dialog */
	private void closeDialog(java.awt.event.WindowEvent evt) {
		setVisible(false);
		dispose();
	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		new JDialog(new javax.swing.JFrame(), true).setVisible(true);
	}

	// Variables declaration - do not modify
	private javax.swing.JLabel jLabel1;
	private javax.swing.JButton jButton1;
	private javax.swing.JProgressBar jProgressBar1;
	// End of variables declaration

}
