package nl.errorsoft.esqlmanager.gui;
/*
 * JDialog.java
 *
 * Created on 9 april 2003, 20:53
 */
import nl.errorsoft.esqlmanager.control.*;
import nl.errorsoft.esqlmanager.domain.*;
import javax.swing.*;
import javax.swing.tree.*;
import javax.swing.event.*;
import java.awt.event.*;
import java.io.*;
/**
 *
 * @author  CoolKillaH
 */
public class ImportExportProgressUI extends javax.swing.JDialog {

    /** Creates new form JDialog */
    public ImportExportProgressUI( JDialog jm ) {

      super( jm, "Import / Export progress" );
      this.getRootPane().setPreferredSize( new java.awt.Dimension( 360, 100 ) );
      initComponents();
		this.setLocation(jm.getLocation().x + (int)((jm.getSize().width - this.getSize().width) / 2), jm.getLocation().y + (int)((jm.getSize().height - this.getSize().height) / 2));
		this.setVisible( true );
		this.toFront();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {
        jProgressBar1 = new javax.swing.JProgressBar();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        getContentPane().setLayout(null);

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        getContentPane().add(jProgressBar1);
        jProgressBar1.setBounds(15, 40, 330, 16);

        jLabel1.setText("Import / Export progress");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(15, 15, 270, 15);

        jButton1.setText("Close");
        getContentPane().add(jButton1);
        jButton1.setBounds(245, 65, 100, 25);
			this.jButton1.setEnabled( false );
        pack();
    }

 	public void setProgressValue( int percentage )
 	{
 		this.jProgressBar1.setValue( percentage );

 		if( percentage == 100 )
 		{
 			this.jButton1.setEnabled( true );
 			showMessage("Process completed successfully!");
 			this.dispose();
 		} 		
 	}
    
	public void showMessage(String message)
	{
		JOptionPane pane = new JOptionPane();  
  		pane.showMessageDialog( this, message, this.getTitle(), JOptionPane.INFORMATION_MESSAGE );  					
	}	
	 	
	public void showErrorMessage(String message)
	{
		JOptionPane pane = new JOptionPane();  
  		pane.showMessageDialog( this, message, this.getTitle(), JOptionPane.WARNING_MESSAGE );  					
	}      

    /** Closes the dialog */
    private void closeDialog(java.awt.event.WindowEvent evt) {
        setVisible(false);
        dispose();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        new JDialog(new javax.swing.JFrame(), true).show();
    }


    // Variables declaration - do not modify
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton jButton1;
    private javax.swing.JProgressBar jProgressBar1;
    // End of variables declaration

}
