package nl.errorsoft.esql.importer.ui;

import nl.errorsoft.esql.error.Dialogs;

import nl.errorsoft.esql.export.ui.ExportAsSQLUI;

import nl.errorsoft.esql.app.ApplicationContext;

import nl.errorsoft.esql.database.Database;

import nl.errorsoft.esql.app.ui.ESQLManagerUI;
import nl.errorsoft.esql.database.ui.DatabaseTreeView;
import nl.errorsoft.esql.importer.control.ImportCC;
import nl.errorsoft.esql.ui.util.ExtentionFileFilter;
/*
 * ExportAsSQLUI.java
 *
 * Created on 29 april 2003, 11:50
 */

import javax.swing.*;

import nl.errorsoft.esql.ui.util.Forms;
import javax.swing.tree.*;
import javax.swing.event.*;
import java.awt.event.*;

/**
 *
 * @author  CoolKillaH
 */
public class ImportAsSQLUI extends javax.swing.JDialog implements ActionListener {
	private ESQLManagerUI jm;
	private ImportCC ecc;
	private DatabaseTreeView dtv;

	public ImportAsSQLUI(ESQLManagerUI jm, ImportCC ecc) {
		super((JFrame) jm, false);
		this.jm = jm;
		this.ecc = ecc;
		this.initComponents();
		this.setTitle("Import as SQL");
		this.setResizable(false);
		this.setDefaultCloseOperation(JDialog.DISPOSE_ON_CLOSE);
		this.setLocationRelativeTo(jm);
		this.setVisible(true);
		this.toFront();
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	private void initComponents() {
		jPanel1 = new javax.swing.JPanel();
		jPanel2 = new javax.swing.JPanel();
		jLabel1 = new javax.swing.JLabel();
		jPanel4 = new javax.swing.JPanel();
		jTextField1 = new javax.swing.JTextField();
		jButton1 = new javax.swing.JButton();
		jButton2 = new javax.swing.JButton();
		jButton3 = new javax.swing.JButton();
		jScrollPane1 = new javax.swing.JScrollPane();

		addWindowListener(new java.awt.event.WindowAdapter() {
			public void windowClosing(java.awt.event.WindowEvent evt) {
				closeDialog(evt);
			}
		});

		jLabel1.setText(
			"<html><body style='width: 300px'>1. Select a database or table you want to import data into. If you don`t want to import data into a specific database or table go to step 2.<br><br>2. Press the \"Browse..\" button to select the file containing the sql-statements.<br><br>3. Press the \"Import\" button to start.</body></html>");
		jLabel1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
		jPanel2.setLayout(new java.awt.BorderLayout());
		jPanel2.add(jLabel1);
		Forms.titled(jPanel2, "Info");

		jTextField1.setEditable(false);
		jTextField1.setColumns(20);
		jButton1.setText("Browse...");
		jButton1.addActionListener(this);
		jPanel4.setLayout(new java.awt.BorderLayout(Forms.GAP, 0));
		jPanel4.add(jTextField1, java.awt.BorderLayout.CENTER);
		jPanel4.add(jButton1, java.awt.BorderLayout.EAST);
		Forms.titled(jPanel4, "Pick File From Disk");

		jButton2.setText("Import");
		jButton2.addActionListener(this);
		jButton3.setText("Close");
		jButton3.addActionListener(this);

		jPanel1 = new Forms.Grid().full(jPanel2).full(jPanel4).full(Forms.buttonRow(jButton2, jButton3)).done();
		jScrollPane1.setPreferredSize(new java.awt.Dimension(180, 300));
		JPanel root = Forms.padded(new JPanel(new java.awt.BorderLayout(Forms.PADDING, 0)));
		root.add(jScrollPane1, java.awt.BorderLayout.WEST);
		root.add(jPanel1, java.awt.BorderLayout.CENTER);
		setContentPane(root);
		pack();
	}

	// Shows the database tree.
	public void showDatabaseTreeView(DatabaseTreeView tv) {
		dtv = tv;
		this.jScrollPane1.getViewport().add(dtv);
		dtv.getSelectionModel().setSelectionMode(TreeSelectionModel.SINGLE_TREE_SELECTION);
	}

	//public void databaseSelected( Database db )
	//{
	//	ecc.showTables( this, db );
	//}

	public DatabaseTreeView getDatabaseTreeView() {
		return dtv;
	}

	public void actionPerformed(ActionEvent e) {
		Object src = e.getSource();

		if (src == jButton3) {
			this.dispose();
		} else if (src == jButton1) {
			JFileChooser chooser = new JFileChooser();

			chooser.addChoosableFileFilter(new ExtentionFileFilter("SQL file", new String[]{".sql"}));
			chooser.setAcceptAllFileFilterUsed(false);
			chooser.setDialogTitle("Select file...");

			try {
				if (chooser.showOpenDialog(jm) == JFileChooser.APPROVE_OPTION) {
					this.jTextField1.setText(chooser.getSelectedFile().getAbsolutePath());
				}
			} catch (Exception err) {
				ApplicationContext.get().errors().report(this, "Choose file", err);
			}
		} else if (src == jButton2) {
			if (jTextField1.getText().trim().length() <= 0) {
				Dialogs.error(this, getTitle(), "Select a file first.");
			} else {
				ecc.importNodesAsSQL(this, dtv.getSelectionPath(), jTextField1.getText());
			}
		}
	}

	/** Closes the dialog */
	private void closeDialog(java.awt.event.WindowEvent evt) {
		setVisible(false);
		dispose();
	}

	// Variables declaration - do not modify
	private javax.swing.JButton jButton2;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JPanel jPanel4;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JButton jButton1;
	private javax.swing.JPanel jPanel2;
	private javax.swing.JButton jButton3;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JTextField jTextField1;
	// End of variables declaration

}
