package nl.errorsoft.esql.blob.ui;

import nl.errorsoft.esql.error.Dialogs;

import nl.errorsoft.esql.app.ApplicationContext;

import nl.errorsoft.esql.blob.control.UDDataCC;

import java.awt.*;
import java.awt.event.*;
import javax.swing.*;

import nl.errorsoft.esql.ui.util.Forms;

/*
 * JDialog.java
 *
 * Created on 9 april 2003, 20:53
 */

/**
 *
 * @author  CoolKillaH
 */
public class DownloadFileUI extends javax.swing.JDialog implements UDDataIF, ActionListener {

	private UDDataCC udcc;

	/** Creates new form JDialog */
	public DownloadFileUI(UDDataCC udcc, JFrame parent) {
		//super(parent, modal);
		this.udcc = udcc;
		initComponents();
		this.setLocation(parent.getLocation().x + (int) ((parent.getSize().width - this.getSize().width) / 2),
			parent.getLocation().y + (int) ((parent.getSize().height - this.getSize().height) / 2));
		this.setVisible(true);
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	private void initComponents() {//GEN-BEGIN:initComponents
		jProgressBar1 = new javax.swing.JProgressBar();
		jLabel1 = new javax.swing.JLabel();
		jButton1 = new javax.swing.JButton();
		jButton2 = new javax.swing.JButton();
		jLabel2 = new javax.swing.JLabel();
		jTextField1 = new javax.swing.JTextField();
		jButton3 = new javax.swing.JButton();

		setTitle("Download data");
		addWindowListener(new java.awt.event.WindowAdapter() {
			public void windowClosing(java.awt.event.WindowEvent evt) {
				closeDialog(evt);
			}
		});
		jLabel1.setText("Press \"Download\" to start the transfer now!");
		jButton1.setText("Download now!");
		jButton2.setText("Cancel");
		jLabel2.setText("Select a location on disk:");
		jButton3.setText("Save as...");
		jLabel2.setFont(jLabel2.getFont().deriveFont(java.awt.Font.BOLD));
		jTextField1.setColumns(24);
		jButton3.addActionListener(this);
		jButton2.addActionListener(this);
		jButton1.addActionListener(this);

		JPanel file = new JPanel(new BorderLayout(Forms.GAP, 0));
		file.add(jTextField1, BorderLayout.CENTER);
		file.add(jButton3, BorderLayout.EAST);
		JPanel content = new Forms.Grid().full(jLabel2).full(file).full(jLabel1).full(jProgressBar1).done();
		JPanel root = Forms.padded(new JPanel(new BorderLayout()));
		root.add(content, BorderLayout.CENTER);
		root.add(Forms.buttonRow(jButton1, jButton2), BorderLayout.SOUTH);
		setContentPane(root);
		pack();
	}//GEN-END:initComponents

	public void setProgressValue(int percentage) {
		this.jProgressBar1.setValue(percentage);

		if (percentage == 100) {
			Dialogs.info(this, getTitle(), "Download completed.");
			this.dispose();
		}
	}

	/** Closes the dialog */
	private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
		setVisible(false);
		dispose();
	}//GEN-LAST:event_closeDialog

	public void actionPerformed(ActionEvent e) {
		if (e.getSource() == jButton3) {
			JFileChooser chooser = new JFileChooser();
			chooser.setAcceptAllFileFilterUsed(true);
			chooser.setDialogTitle("Save data...");

			try {
				if (chooser.showSaveDialog(this) == JFileChooser.APPROVE_OPTION) {
					jTextField1.setText(chooser.getSelectedFile().getAbsolutePath());
				}
			} catch (Exception err) {
				ApplicationContext.get().errors().report(this, "Choose file", err);
			}
		} else if (e.getSource() == jButton2) {
			this.dispose();
		} else if (e.getSource() == jButton1) {
			udcc.downloadFile(jTextField1.getText());
		}
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton jButton2;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JButton jButton1;
	private javax.swing.JButton jButton3;
	private javax.swing.JTextField jTextField1;
	private javax.swing.JProgressBar jProgressBar1;
	// End of variables declaration//GEN-END:variables

}
