package nl.errorsoft.esql.blob.ui;

import nl.errorsoft.esql.error.Dialogs;

import nl.errorsoft.esql.app.ApplicationContext;

import nl.errorsoft.esql.blob.control.UDDataCC;

import java.awt.*;
import java.awt.event.*;
import java.nio.file.Files;
import java.nio.file.Path;
import javax.swing.*;

import nl.errorsoft.esql.ui.util.FormDialog;
import nl.errorsoft.esql.ui.util.Forms;

/*
 * JDialog.java
 *
 * Created on 9 april 2003, 20:53
 */

/**
 *
 * @author  CoolKillaH
 */
public class DownloadFileUI extends FormDialog implements UDDataIF, ActionListener {

	private UDDataCC udcc;
	/** True while a transfer runs, the window cannot be closed then. */
	private boolean busy;

	/** Creates new form JDialog */
	public DownloadFileUI(UDDataCC udcc, JFrame parent) {
		super(parent, "Download data", true);
		this.udcc = udcc;
		initComponents();
	}

	@Override
	public void open() {
		showDialog();
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	private void initComponents() {
		jProgressBar1 = new javax.swing.JProgressBar();
		jLabel1 = new javax.swing.JLabel("Click Download to start the transfer.");
		jButton1 = Forms.button("&Download");
		jButton2 = Forms.button("Cancel");
		jTextField1 = new javax.swing.JTextField(24);
		jButton3 = Forms.button("&Save as...");
		jButton3.addActionListener(this);
		jButton2.addActionListener(this);
		jButton1.addActionListener(this);

		// A transfer in progress cannot be closed, closeDialog decides (also for Esc).
		setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
		addWindowListener(new java.awt.event.WindowAdapter() {
			public void windowClosing(java.awt.event.WindowEvent evt) {
				closeDialog(evt);
			}
		});

		JPanel file = new JPanel(new BorderLayout(Forms.GAP, 0));
		file.add(jTextField1, BorderLayout.CENTER);
		file.add(jButton3, BorderLayout.EAST);
		JPanel content = new Forms.Grid().row(Forms.label("Save &as:", jTextField1), file).full(jLabel1).full(jProgressBar1).done();
		layoutDialog(content, jButton1, jButton2);
		setInitialFocus(jTextField1);
	}

	private void setBusy(boolean busy) {
		this.busy = busy;
		if (busy) {
			showError(null);
		}
		jButton1.setEnabled(!busy);
		jButton2.setEnabled(!busy);
		jButton3.setEnabled(!busy);
	}

	@Override
	public void transferEnded() {
		setBusy(false);
	}

	@Override
	public void setProgressValue(int percentage) {
		this.jProgressBar1.setValue(percentage);

		if (percentage == 100) {
			this.dispose();
		}
	}

	/** Closes the dialog */
	private void closeDialog(java.awt.event.WindowEvent evt) {
		if (!busy) {
			dispose();
		}
	}

	public void actionPerformed(ActionEvent e) {
		if (e.getSource() == jButton3) {
			JFileChooser chooser = new JFileChooser();
			chooser.setAcceptAllFileFilterUsed(true);
			chooser.setDialogTitle("Save data...");

			try {
				if (chooser.showSaveDialog(this) == JFileChooser.APPROVE_OPTION) {
					jTextField1.setText(chooser.getSelectedFile().getAbsolutePath());
				}
			} catch (Exception err) {
				ApplicationContext.get().errors().report(this, "Choose file", err);
			}
		} else if (e.getSource() == jButton2) {
			this.dispose();
		} else if (e.getSource() == jButton1) {
			String file = jTextField1.getText().trim();

			if (file.isEmpty()) {
				showError("Enter the file to save to.");
			} else if (!Files.exists(Path.of(file))
				|| Dialogs.confirmDestructive(this, getTitle(), "Overwrite the existing file '" + file + "'?", "Overwrite")) {
				setBusy(true);
				udcc.downloadFile(file);
			}
		}
	}

	// Variables declaration
	private javax.swing.JButton jButton2;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JButton jButton1;
	private javax.swing.JButton jButton3;
	private javax.swing.JTextField jTextField1;
	private javax.swing.JProgressBar jProgressBar1;
	// End of variables declaration

}
